server:
  host: localhost
  port: 8080
database:
  username: root
  password: 123456
  host: localhost
  port: 3310
  databaseName: shop_dev
auth:
  jwtSecretKey: Khaideptrai
  exp: 1440
log:
  level: INFO #ERROR
