server:
  host: localhost
  port: 8080
database:
  username: root
  password: 123456
  host: localhost
  port: 3310
  databaseName: shop_dev
auth:
  jwtSecretKey: "MIIJKAIBAAKCAgEAxljaqvjPLutoXXGfCVAJKqgMjMkOs7nSpn2rDBoqVSfG7bsy
8A2IDxN1lJlrWo2R+dh+uPPalDeP2/h4MoeQNMVTBV1kcVOYCbG47m9g+SEtOvP/
IcseZ9vH9TT4bZTUr+xbF5Ir//pdZjbA9t04Or1n88xpl05CWjILRqCK/i2zVIGT
PhEqrMyTEzth+vZr2K7wFcKp6jd9T7nDSD9zAAqC9i8nfyurANm/N9D4zvhBL9uR
EErtkPorgI3N5RbY0bprOtFGe+r/REmwNhTKjvEU2Apl6q++ampC9/Rrb4Q8f1dA
2xK9dDvDyJjwUcVGUqYQXVM4wsB55e1BJ0jpWQzLjPgH/Zl+jjv5DsEnjkrdh3KF
9VHLvOaUDaA+X5z/V2RHr7yk3B8QuLiSejJAyAwwE6uc7RCZK5vTZwUuRB+4Mb/V
O9mEZiYg8c7hT9rVRyZ90uBWCVPseCbjVXSGhKAvT20vWyQva7cj3Lm0hIFm7LaG
Xjr2RE0U95xfjaoCNd6bp+F2Od8/jvlVDkWqI8HRO8IPdw5BwcnZtxtc/1/OW/5T
f1yAuXGB7WvL7uh32xGpDiqgbJ+/HWSJz52jdFhYn53g0GBmVL8PpRMWZBrW5fxI
p3iOdP1s6ziACTFJZkMYZA2I83N1b+hTFImMNezVngliAwuI4yYn8gAQFMECAwEA
AQKCAgAHcfZjTIuaW0PDniw2EUcGzuAJuNJQdL0verAc+C52m9OfwNMcp6Vfy38y
YL/i2kWMd0/qaVzfC2be/uikHOqQ0IdZQDQw/M5MLtueN5gQQeqMt/PvtMwjYeCT
l7Vrh5akM98Hd3knVqKC37NGkO83ZTytrhKYl1tuP0qlEAmnmNeOaH66abKMYfFz
W1tGLFHIBGkGqBPwsryFbZei8p7CdaKM0yBMabs1gPbohXORcUghH8DGN8nLE1jm
rmv4GW9yD+lOf+SBakTCr3Fp1kX0L6B0q48/y/D91ZdF72rI+NG8he3tSzrJTiT/
Np5us1T8bTdYCXOr+8WXl9xGOTppCGEkzzmk9kFIdlZ8MgExOSOwprLlV5MEpv8j
CxLCFM8t1aO91XlXCgfZUqWYnWwTC9duSk/MatziLyyJc2K3XHtJ+40dTdvJrP7Z
AvmN5+NeQnD5+Cqrt8eBd/TYM/LqIVHeB1mAN+LL0EPvdywti/beZzMFwBFYpf61
ZCewkI3phheXVs4/6D3XREQKraSRthoKvNKJzTmo/2bGrCiLsGnG64fI70YuIoyd
VrR88Jl2eTdmpgSgrQZnBn8UQI+YBTELnG/nhOGPjZ/ZSDGjOsQ/9VZuA+IhdUrb
eiB9cy+P4BOUOAOxqOOYPThcV8OBjaY8hv9AcSL4/wHAINdFMQKCAQEA6GzqNbis
7OHg3hk1gE5wWgD/1VCdyNL1Ea2pUyTRu6vEz8hSEKQnF3yIrWyFyEG0t6f0jWpG
1Bc8CDimhJbYZw9gMxAHtr753tR5fHYp2O7OIYK6aPDw8wFAfPcLvdcSvRYd8Cze
dvTcLIr/d9HOu0izcjgq0kdMaNiyqMSqi7A4jJafBWCpD/KQgs+q/5EQu4wuFalS
zxOXhUqhA9moGSvA6mXYW9Mwh5KXJhRAJfojWomYvueKaZ0r4rTy3LOgN8+MWRWf
1zuqZw0HflwDzT5akJN4Cr32tug7+4iYgZ3RYuLpeg7Gids0KiDDcnz7GvoBZcHM
dctmdUsQaj0pSwKCAQEA2ncSR0H5r7Veu6R54PbAdLiLhzGXYc5MaLG7Ec2sunus
uCHDHOUuOg/iXAPl8nU+oUg2P0gCyRFvx1qVOCUUY+IBil3h0rxQTrymwOBxM017
VCZYCQTzfiNIXsFlhT4BePPMNeDQne4AB4BVO63FKSUNwrNA0uyAE8GJViVtSpoz
2Zq9RGZ0Pq0zhmkxJbU9NIATM/ePQBGgyp5FqAlkfxgPfqAt+AdM5Xx1+pm/tpX1
CwMqwzZQWTHBiy+8vTTeCR0uK95XlSA2tVCR69a962mj0JxG6kLTQKhnH2pfPK1Y
I7MonXoAT983FEzLdSZnPUZdPT+zAZzL/ZXKa9geowKCAQEAtjmeLtxJh7dYjAkL
rzrQT2B1NBNugaMTzPZwyOUXIqJ7PcT6wl1Q4NMcfYuWH/mT7GHcFHt8aJCG2pM/
yrhRlguyCpbI1XhJg3DmhrRF/vTL2+4YpGozHvKeUtuF8yMKaAFNG56yFGXJsYqQ
3Ko8AQ3w0t5ChHat643qFPOMGtTgoSj+KEMuiXhN4KFcmd5sVf6DqywD5qKfqztl
nhUp/AIX0C5lQSkE5WYC5zH9UUkaKsOyZAo4tLErVSU1O+AA/4DTsoyHs0HuSbkn
ZORTfrkiXDOibBmfsqvFS2I+33CSV4s8LhwjgLXB4j2pvrtKTE4yhks5OClufQuL
JSAqnQKCAQB9oavpPo+P9AUec1+Dd2MFvHrArEwZ+sEGE+84Ncb3Ftgkq4XAwCrt
SOUrdTJvU+1IYnaPvaGcb2KQig710pz/M6EfKQ4MWi70mJhsoqV2k0AxDDvkM+yy
xSeBFkaDcTz3iXwOH9LYf12U8sARKcUP/DcFmH/WzBp7QfjwiWVoWXUn1kyxYRnI
UWIoEaYpwSgJYP2qDNtcRMbqvkngcEZSsEt4zjShRdF6xzAxhOky3tmkE5Yr3Lgo
EuzyVel8BUMKirValOpY38WWT1cbAMsG7iE+fiBp5zQFItLqxgkuo6DkJstchCRZ
ykuqaN8353XHTwefiVovuzO0CMf3bLlxAoIBAHY78xDyWv9VxhEESbcm/QO2Era9
CRKUxQ9+2v+WwRuaRuyLrB4xkJEkJuYaTp21bFAm3VFswqF7grhTFyVhKcqrqo1H
EFRCm+Uwg4+2LnXAMYTX58SKyiK45tvULLGEna6yMk9FscFQjiTxWJ58y/qEq84J
GQU+vTEovV1fgViJTUwKkkmvDjV2N18eKMcHSky85FRPVVhnHYUdkk38PSLg7clw
J0YU95JinHt2BA16vSzrI51JLiOOOwxEdc61hEjZ8xdMGAYrblYyazKtSbHw0YHS
zmf5uwxgRsXFs0gMglB39WuKNnQ+A1uHJaXQFnuMiVa99jQgdFplLrfli0c="
  exp: 1440
log:
  level: INFO #ERROR
